version: '3'

services:
  quasarapp:
    image: quasarapp
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - quasarapp

    # ports:
    #   - "8000:8000"
    #   - 3000:3000

# ssh root@84.38.180.213
# qy66y67weu

